### PR TITLE
External project: add yaehmop

### PR DESCRIPTION
**Pull request by psavery**
Hi Marcus @cryos,

Let me know what you think about this update. It works fine on linux, but I am not sure if it works on other operating systems yet.

A few things that surprised me while I was working through it (that I hope are the same on Mac and Windows also):
1. cmake appears to unzip and untar the .tgz file automatically. I was going to tell it to do it myself, but it does it automatically. I'm guessing it just recognizes the extension.
2. The unzipped and untarred file already has executable permissions. I was expecting to have to modify the permissions myself (I was looking at `cmake -E` for an option to modify permissions, but couldn't find anything). But to my surprise, it is already executable. I hope it retains its executable permissions on Mac and Windows as well.
3. It puts the unzipped and untarred binary in the source dir, so I am able to tell it to install the binary via `cmake -E copy <SOURCE_DIR>/${YAEHMOP_NAME} ...` . I hope the same is true on Windows and Mac.

Anyways, let me know if I should change anything, or if there is a better way of doing anything.

Thanks,
Patrick

### CODE REVIEW

**Comment by cryos** [comment]
Missed this, will look soon.

**Comment by psavery** [comment]
I merged master into this and resolved the conflicts.

**Comment by ghutchis** [comment]
I merged #52 - not sure if it's worth having this instead? What do you think @psavery

**Comment by psavery** [comment]
It's been a while, so I can't fully remember. But it looks like #52 might build yaehmop, whereas this one downloads pre-built binaries.

The problem with building yaehmop at that time was that it required a fortran compiler, which we do not want to add as a dependency to Avogadro2. I think yaehmop no longer requires a fortran compiler, but I can't remember all of the details - maybe fortran is required to link to blas and lapack? Not sure.

Anyways, I think this one was good at the time, because it, by default, downloaded the pre-built binaries, but also offered an option for the user to build the source.

Sorry that I cannot fully remember everything...

**Pull request closed without merging**
