### PR TITLE
Update spglib, download location unclear

### PR DESCRIPTION
**Pull request by cryos**
Moved it to GitHub, it looks like SourceForge is no longer used, the web
page didn't contain a download link as far as I could tell.

### CODE REVIEW

**Comment by ghutchis** [comment]
I'm fine with this - paging @psavery - is the new spglib okay?

**Comment by psavery** [comment]
Yes, I'm fine with updating spglib. But it looks like it has some linking errors with AvogadroCore. We might want to look into those before merging.

**Comment by psavery** [comment]
I sent a PR [here](https://github.com/cryos/openchemistry/pull/1) to fix the linking issues. 

However, it looks like the spglib functions may have changed a little bit - some of the spglib functions are now failing when they run. So I may need to look into fixing the api.

Also, I noticed that spglib is off by default now in avogadolibs. It is because in [this commit](https://github.com/OpenChemistry/avogadrolibs/commit/e7071afbd9afbd83bf1e72c68f6d8f8f86c66aab), sometimes, the definition was called `USE_LIBSPG`, and sometimes, it was called `USE_SPGLIB`. I will look into fixing that here soon.

**Comment by cryos** [comment]
Will check it builds soon, catching up.

**Comment by psavery** [comment]
I double-checked this again really quickly, and this time, the spglib features seemed to work fine in the GUI. I'm not sure what the problem was that I mentioned in my previous comment.

The tests that I wrote for the spglib features (located [here](https://github.com/OpenChemistry/avogadrolibs/blob/master/tests/core/spacegrouptest.cpp)) seem to be fairly comprehensive. They passed for me. As long as they pass here, this may be ready to merge.

**Pull request merged**
